// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoutingIguana.Data;

#nullable disable

namespace ShoutingIguana.Data.Migrations
{
    [DbContext(typeof(SqliteShoutingIguanaDbContext))]
    [Migration("20251029112738_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ShoutingIguana.Core.Models.CrawlCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCrawledUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlsAnalyzed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrlsCrawled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IsActive");

                    b.ToTable("CrawlCheckpoints", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.CrawlQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnqueuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HostKey");

                    b.HasIndex("ProjectId", "Address")
                        .IsUnique();

                    b.HasIndex("ProjectId", "State", "Priority");

                    b.ToTable("CrawlQueue", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.CustomExtractionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectorType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CustomExtractionRules", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Finding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Severity");

                    b.HasIndex("TaskKey");

                    b.HasIndex("UrlId");

                    b.ToTable("Findings", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Header", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.ToTable("Headers", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Hreflang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsXDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsXDefault");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("UrlId");

                    b.HasIndex("UrlId", "LanguageCode");

                    b.ToTable("Hreflangs", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SrcUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SrcUrl");

                    b.HasIndex("UrlId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DomPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElementHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElementTag")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElementWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlSnippet")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNofollow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSponsored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUgc")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentTag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelAttribute")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToUrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromUrlId");

                    b.HasIndex("IsNofollow");

                    b.HasIndex("ToUrlId");

                    b.HasIndex("ProjectId", "LinkType");

                    b.ToTable("Links", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Redirect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.HasIndex("UrlId", "Position");

                    b.ToTable("Redirects", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.StructuredData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationErrors")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsValid");

                    b.HasIndex("SchemaType");

                    b.HasIndex("Type");

                    b.HasIndex("UrlId");

                    b.HasIndex("UrlId", "Type");

                    b.ToTable("StructuredData", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheControl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalHtml")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalHttp")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalIssues")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentEncoding")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentLanguageHeader")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscoveredFromUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCrossDomainCanonical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHsts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasJsChanges")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMetaRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMultipleCanonicals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRobotsConflict")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlLang")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsIndexable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRedirectLoop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSoft404")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsChangedElements")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCrawledUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkHeader")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetaRefreshDelay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaRefreshTarget")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaRobots")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RedirectChainLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedirectTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedHtml")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RobotsAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RobotsNoarchive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RobotsNofollow")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RobotsNoimageindex")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RobotsNoindex")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RobotsNosnippet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RobotsSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SimHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("XRobotsTag")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DiscoveredFromUrlId");

                    b.HasIndex("HasMultipleCanonicals");

                    b.HasIndex("Host");

                    b.HasIndex("HtmlLang");

                    b.HasIndex("IsIndexable");

                    b.HasIndex("NormalizedUrl");

                    b.HasIndex("RobotsNoindex");

                    b.HasIndex("SimHash");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Urls", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.CrawlCheckpoint", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.CrawlQueueItem", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany("CrawlQueue")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.CustomExtractionRule", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Finding", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Findings")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Header", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Headers")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Hreflang", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Hreflangs")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Image", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Images")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Link", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "FromUrl")
                        .WithMany("LinksFrom")
                        .HasForeignKey("FromUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany("Links")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoutingIguana.Core.Models.Url", "ToUrl")
                        .WithMany("LinksTo")
                        .HasForeignKey("ToUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUrl");

                    b.Navigation("Project");

                    b.Navigation("ToUrl");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Redirect", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Redirects")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.StructuredData", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("StructuredData")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Url", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "DiscoveredFromUrl")
                        .WithMany()
                        .HasForeignKey("DiscoveredFromUrlId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany("Urls")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscoveredFromUrl");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Project", b =>
                {
                    b.Navigation("CrawlQueue");

                    b.Navigation("Links");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Url", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Headers");

                    b.Navigation("Hreflangs");

                    b.Navigation("Images");

                    b.Navigation("LinksFrom");

                    b.Navigation("LinksTo");

                    b.Navigation("Redirects");

                    b.Navigation("StructuredData");
                });
#pragma warning restore 612, 618
        }
    }
}
