// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoutingIguana.Data;

#nullable disable

namespace ShoutingIguana.Data.Migrations
{
    [DbContext(typeof(SqliteShoutingIguanaDbContext))]
    [Migration("20251024100212_AddStage2Tables")]
    partial class AddStage2Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ShoutingIguana.Core.Models.CrawlQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnqueuedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HostKey");

                    b.HasIndex("ProjectId", "State", "Priority");

                    b.ToTable("CrawlQueue", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Finding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Severity");

                    b.HasIndex("TaskKey");

                    b.HasIndex("UrlId");

                    b.ToTable("Findings", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Header", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.ToTable("Headers", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SrcUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SrcUrl");

                    b.HasIndex("UrlId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnchorText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("FromUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToUrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromUrlId");

                    b.HasIndex("ToUrlId");

                    b.HasIndex("ProjectId", "LinkType");

                    b.ToTable("Links", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Redirect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.HasIndex("UrlId", "Position");

                    b.ToTable("Redirects", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscoveredFromUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCrawledUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaRobots")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedirectTarget")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RobotsAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("DiscoveredFromUrlId");

                    b.HasIndex("Host");

                    b.HasIndex("NormalizedUrl");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Urls", (string)null);
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.CrawlQueueItem", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany("CrawlQueue")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Finding", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Findings")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Header", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Headers")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Image", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Images")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Link", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "FromUrl")
                        .WithMany("LinksFrom")
                        .HasForeignKey("FromUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany("Links")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoutingIguana.Core.Models.Url", "ToUrl")
                        .WithMany("LinksTo")
                        .HasForeignKey("ToUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUrl");

                    b.Navigation("Project");

                    b.Navigation("ToUrl");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Redirect", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "Url")
                        .WithMany("Redirects")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Url");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Url", b =>
                {
                    b.HasOne("ShoutingIguana.Core.Models.Url", "DiscoveredFromUrl")
                        .WithMany()
                        .HasForeignKey("DiscoveredFromUrlId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShoutingIguana.Core.Models.Project", "Project")
                        .WithMany("Urls")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscoveredFromUrl");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Project", b =>
                {
                    b.Navigation("CrawlQueue");

                    b.Navigation("Links");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("ShoutingIguana.Core.Models.Url", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Headers");

                    b.Navigation("Images");

                    b.Navigation("LinksFrom");

                    b.Navigation("LinksTo");

                    b.Navigation("Redirects");
                });
#pragma warning restore 612, 618
        }
    }
}
